[phases.setup]
nixPkgs = ['nodejs_18', 'pnpm']

[phases.install]
cmds = ['pnpm install --frozen-lockfile']

[phases.build]
dependsOn = ['install']

[start]
cmd = 'cd apps/web && pnpm start -- -p $PORT'
